import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  // Dictionary with translations
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {},
    'ar': {
      'Login': 'تسجيل الدخول',
      'Register': 'إنشاء حساب',
      'Logout': 'تسجيل الخروج',
      'Email': 'البريد الإلكتروني',
      'Dont have an account': 'ليس لديك حساب؟',
      'Already have an account': 'لدي حساب؟',
      "Welcome to Maintenance App!": "مرحبا بك في وثيق للصيانة!",
      "404": "404",
      "Notifications": "إعلام",
      "New": "جديد",
      "FormErrorCaption": "إدخال خاطئ",
      "FormErrorMessage":
          "لقد أدخلت معلومات غير صالحة أو غير كاملة. يرجى تصحيح أي أخطاء والمحاولة مرة أخرى.",
      "Appointments": "المواعيد",
      "Logout": "الخروج",
      "ManageProducts": "إدارة المخازن",
      "branchesReport": "تقرير المناطق",
      "Administrative settings": "إعدادات إدارية",
      "workersReport": "تقرير المحاسبين",
      "servicesReport": "تقرير المشاريع",
      "productsReport": "تقرير المنتجات",
      "clientsReport": "تقرير العملاء",
      "driversReport": "تقرير السائقين",
      "employeesReport": "تقرير الموظفين",
      "paidOffersReport": "تقرير العروض المدفوعة",
      "Invoice": "فاتورة",
      "Message": "رسالة",
      "Branches": "الفروع",
      "Neighborhoods": "الأحياء",
      "Regions": "المناطق",
      "Companies": "الشركات",
      "SeasonalOffers": "العروض الموسمية",
      "PaidOffers": "العروض المدفوعة",
      "NewReservation": "حجز جديد",
      "Reservations": "الحجوزات",
      "ProductCategories": "تصنيف المنتجات",
      "ProductUnits": "الوحدات",
      "GiftCards": "كروت هدايا",
      "DailyReservations": "الجدول اليومي",
      "Groups": "المجموعات",
      "NoWidgets1": "لم يتم عرض أية أدوات. اذهب إلى",
      "NoWidgets2": "لتكوين الأدوات المتاحة",
      "Total income": "إجمالي الدخل",
      "pageNotFound": "الصفحة التي تبحث عنها غير موجودة",
      "backToHome": "العودة إلى الصفحة الرئيسية",
      "Profile": "الملف الشخصي",
      "Preferences": "التفضيلات",
      "UserProfile": "ملف تعريفي للمستخدم",
      "UserPreferences": "خيارات المستخدم",
      "UserDepartments": "أقسام المستخدم",
      "UsersManagements": "إدارة المستخدمين",
      "RolesManagement": "إدارة الأدوار",
      "ReloadPreferences": "إعادة تحميل التفضيلات:",
      "ReloadPreferencesHint":
          "(تحميل التفضيلات الافتراضية (يتم تجاهل التغييرات المحلية",
      "Language": "اللغة",
      "Default": "إفتراضي",
      "English": "الإنجليزية",
      "French": "الفرنسية",
      "German": "الألمانية",
      "Portuguese": "البرتغالية",
      "Arabic": "العربية",
      "Korean": "الكورية",
      "LanguageHint": "اختيار اللغة المفضلة لحسابك",
      "HomePage": "الصفحة الرئيسية:",
      "Dashboard": "داشبورد",
      "Customers": "العملاء",
      "Products": "المنتجات",
      "Orders": "الأوامر",
      "About": "تعليمات",
      "Settings": "إعدادات",
      "HomePageHint": "حدد الصفحة الافتراضية للانتقال إلى تسجيل الدخول",
      "Theme": "المظهر",
      "DefaultColor": "<span class='default-theme-option'>اللون المفضل</span>",
      "RedColor": "<span class='red-theme-option'>الأحمر</span>",
      "OrangeColor": "<span class='orange-theme-option'>البرتقالي</span>",
      "GreenColor": "<span class='green-theme-option'>الأخضر</span>",
      "GrayColor": "<span class='gray-theme-option'>الرمادي</span>",
      "BlackColor": "<span class='black-theme-option'>الأسود</span>",
      "ThemeHint": "حدد اللون الافتراضي لحسابك",
      "DashboardStatistics": "إحصائيات لوحة التحكم",
      "DashboardStatisticsHint": "عرض الرسم البياني على لوحة التحكم",
      "DashboardNotifications": "إشعارات لوحة التحكم",
      "DashboardNotificationsHint": "عرض إشعارات التطبيق على لوحة التحكم",
      "DashboardTodo": "لوحة التحكم للواجبات:",
      "DashboardTodoHint": "يظهر الوحة للواجبات على لوحة التحكم",
      "DashboardBanner": "شعار لوحة التحكم:",
      "DashboardBannerHint": "عرض معلومات الراية على لوحة التحكم",
      "ResetDefault": "اعادة تشغيل الأصل",
      "SetDefault": "تعيين الأصل",
      "NewUser": "مستخدم جديد",
      "Create an account": "إنشاء حساب",
      "EditUser": "تعديل المستخدم \"{{name}}\"",
      "Title": "عنوان",
      "UserName": "اسم المستخدم",
      "JobId": "المسمى الوظيفي: ",
      "UserNameRequired":
          "(مطلوب اسم المستخدم (الحد الأدنى من 2 والحد الأقصى 200 حرفا",
      "PasswordHint": "كلمة السر مطلوبة عند تغيير اسم المستخدم",
      "CurrentPasswordRequired": "كلمة السر الحالية مطلوبة",
      "ChangePassword": "غير كلمة السر",
      "CurrentPassword": "كلمة السر الحالية:",
      "NewPassword": "كلمة سر جديدة:",
      "NewPasswordRequired": "الحد الأدنى من 6 أحرف) مطلوب كلمة سر)",
      "ConfirmPassword": "تأكيد كلمة السر:",
      "ConfirmationPasswordRequired": "مطلوب كلمة سر التأكيد",
      "PasswordMismatch": "لا تتطابق كلمة السر الجديدة وكلمة سر التأكيد",
      "Roles": "الأدوار",
      "FullName": " الاسم الكامل",
      "RoleRequired": " مطلوب دور",
      "Enabled": "مفعل",
      "Unblock": "رفع الحظر",
      "NewCustomer": "عميل جديد",
      "EditCustomer": "تعديل العميل \"{{name}}\"",
      "CustomerNameRequired":
          "اسم العميل مطلوب (بحد أدنى 2 حرف بحد أقصى 200 حرف)",
      "EmailRequired": "عنوان البريد الإلكتروني مطلوب (بحد أقصى 200 حرف)",
      "InvalidEmail": "البريد الإلكتروني المحدد غير صالح",
      "PhoneNumber": "رقم الجوال",
      "Address": "العنوان",
      "Map": "رابط خريطة قوقل",
      "Gender": "الجنس",
      "City": "المدينة",
      "NewRole": "دور جديد",
      "RoleDetails": "تفاصيل الدور \"{{name}}\"",
      "EditRole": "  تعديل الدور\"{{name}}\"",
      "Users": "المستخدمين",
      "Role": "الدور",
      "RoleNameRequired": "(اسم الدور مطلوب (بحد أدنى 2 و 200 حرف كحد أقصى",
      "SelectAll": "اختر الكل",
      "SelectNone": "لا تختر شيء",
      "Close": "إغلاق",
      "Saving": "جار الحفظ...",
      "Pin": "رفع الأولوية",
      "Date": "التاريخ",
      "Notification": "إشعار",
      "HideCompleted": "إكتمال الإخفاء",
      "Task": "مهمة",
      "NewTask": "مهمة جديدة",
      "TaskNameRequired": "مطلوب اسم المهمة",
      "Important": "وضع علامة لإظهار الأهمية",
      "AddTask": "إضافة مهمة",
      "Reset": "مسح",
      "Reload": "تحميل",
      "Region": "المنطقة",
      "Working days": "أيام الدوام",
      "Success": "نجاح العملية",
      "Failed": "فشل العملية",
      "Save changes": "حفظ التغيرات",
      "WasSavedSuccessfully": "تم الحفظ بنجاح",
      "Tax": "الضريبة",
      "AttemptingLogin": "جاري تسجيل الدخول",
      "Edit": "تعديل",
      "Delete": "حذف",
      "Tax percentage": "نسبة الضريبة",
      "Serial": "تسلسل",
      "Icon": "الأيقونة",
      "PrintInvoice": "طباعة الفاتورة",
      "Search": "بحث",
      "Description": "الوصف",
      "Name": "الاسم",
      "Number": "الرقم",
      "Branch": "الفرع",
      "Required": "مطلوب",
      "Price": "السعر",
      "Period": "الفترة",
      "Duration": "المدة",
      "StartDate": "يبدأ في",
      "EndDate": "تاريخ الانتهاء",
      "All": "الجميع",
      "Discount percentage": "نسبة الخصم",
      "Offers": "العروض",
      "NumberOfUsers": "عدد المستخدمين",
      "Amount": "المبلغ",
      "Company": "الشركة",
      "Services": "المشاريع",
      "Save": "حفظ",
      "Cancel": "إلغاء",
      "Product category": "تصنيف المنتج",
      "Product unit": "الوحدة",
      "Male": "ذكور",
      "Female": "إناث",
      "Username": "اسم المستخدم",
      "Password": "كلمة السر",
      "Welcome": "أهلا بك",
      "Remember me": "تذكرني",
      "SessionFor": "جلسة",
      "Restored": "تمت الاستعادة",
      "Unable to login": "لا يمكن الدخول",
      "The password or username is incorrect":
          "كلمة السر أو اسم المستخدم غير صحيح",
      "Welcome back": "مرحبا بك مجددا",
      "Session ended": "انتهت الجلسة",
      "Your session has expired": "انتهت الجلسة، من فضلك حاول مرة أخرى",
      "Loading": "تحميل",
      "Add": "إضافة",
      "Details": "تفاصيل",
      "CommissionAmount": "مقدار العمولة",
      "DeliveryFee": "رسوم التوصيل",
      "Riyal": "ريال",
      "ProductName": "اسم المنتج",
      "BuyingPrice": "سعر الشراء",
      "SellingPrice": "سعر البيع",
      "UnitsInStock": "عدد الوحدات في المخزن",
      "NewProduct": "منتج جديد",
      "EditProduct": "تعديل المنتج",
      "ChangesSuccessfullyDone": "تم حفظ التعديلات بنجاح",
      "AddedSuccessfullyDone": "تمت عملية الإضافة بنجاح",
      "Sunday": "الأحد",
      "Monday": "الاثنين",
      "Tuesday": "الثلاثاء",
      "Wednesday": "الأربعاء",
      "Thursday": "الخميس",
      "Friday": "الجمعة",
      "Saturday": "السبت",
      "BranchName": "اسم الفرع",
      "New branch": "فرع جديد",
      "EditBranch": "تعديل الفرع",
      "NeighborhoodName": "اسم الحي",
      "NewNeighborhood": "حي جديد",
      "EditNeighborhood": "تعديل الحي",
      "RegionName": "اسم المنطقة",
      "NewRegion": "منطقة جديدة",
      "EditRegion": "تعديل المنطقة",
      "CompanyName": "اسم الشركة",
      "NewCompany": "شركة جديدة",
      "EditCompany": "تعديل الشركة",
      "ProductCategoryName": "اسم التصنيف",
      "NewProductCategory": "تصنيف جديد",
      "EditProductCategory": "تعديل التصنيف",
      "ProductUnitName": "اسم الوحدة",
      "NewProductUnit": "وحدة جديدة",
      "EditProductUnit": "تعديل الوحدة",
      "ServiceName": "اسم المشروع",
      "NewService": "مشروع جديد",
      "EditService": "تعديل المشروع",
      "SeasonalOfferName": "اسم العرض",
      "NewSeasonalOffer": "عرض جديد",
      "EditSeasonalOffer": "تعديل العرض",
      "PaidOfferName": "اسم العرض",
      "NewPaidOffer": "عرض جديد",
      "EditPaidOffer": "تعديل العرض",
      "Code": "الكود",
      "NewGiftCard": "كرت جديد",
      "EditGiftCard": "تعديل الكرت",
      "Addresses": "العناوين",
      "GoogleMapLink": "رابط خرائط قوقل",
      "CustomerName": "اسم العميل",
      "SalesProduct": "منتج حجوزات",
      "ServicesAndSales": "مشاريع وحجوزات",
      "ProductType": "نوع المنتج",
      "ProductNumber": "رقم المنتج",
      "ExpirationDate": "تاريخ الانتهاء",
      "Taxes": "الضرائب",
      "New tax": "ضريبة جديدة",
      "Laborer name": "اسم المحاسب",
      "Driver name": "اسم السائق",
      "Employee name": "اسم الموظف",
      "TaxName": "عنوان الضريبة",
      "ReservationDate": "تاريخ الحجز",
      "PersonCount": "عدد الأشخاص",
      "best test": "أفضل تجربة",
      "DiscountAmount": "مبلغ الخصم",
      "Branch name": "اسم الفرع",
      "Price after discount": "السعر بعد الخصم",
      "Workers": "المحاسبين",
      "Total service time in minutes": "إجمالي مدة المشروع بالدقائق",
      "Reservation status": "حالة الحجز",
      "Neighborhood": "الحي",
      "Customer": "العميل",
      "Service": "الخدمة",
      "Product": "المنتج",
      "Payment method": "طريقة الدفع",
      "Total": "إجمالي",
      "Notes": "ملاحظات",
      "Cash": "كاش",
      "Online": "أونلاين",
      "Transformation": "تحويل",
      "Coupon": "كوبون",
      "Apply": "تطبيق",
      "Time": "الوقت",
      "Drivers": "السائقين",
      "Period in minutes": "المدة بالدقائق",
      "New reservation": "حجز جديد",
      "Implementation date": "موعد التنفيذ",
      "Client name": "اسم العميل",
      "Day": "اليوم",
      "Service completion date": "موعد انتهاء المشروع",
      "Export to pdf": "تصدير إلى بي دي إف",
      "Export to excel": "تصدير إلى إكسل",
      "Send SMS to customer": "إرسال رسالة للعميل",
      "No data matching the filter": " لا توجد بيانات مطابقة للبحث",
      "Created by": "تم بواسطة",
      "Status": "الحالة",
      "Must be greater than start date":
          "يجب أن يكون تاريخ الانتهاء أكبر من تاريخ البدء",
      "Count": "العدد",
      "Is enabled": "مفعل",
      "New coupon": "كوبون جديد",
      "Edit coupon": "تعديل الكوبون",
      "Coupons": "الكوبونات",
      "Yes": "نعم",
      "No": "لا",
      "Code exist before": "الرمز موجود مسبقا",
      "Save error": "خطأ في الحفظ",
      "Save Error": "خطأ في الحفظ",
      "One or more errors occurred while saving your changes:":
          "حدث خطأ واحد أو أكثر أثناء حفظ التغييرات: ",
      "User Permissions": "صلاحيات المستخدمين",
      "Role Permissions": "صلاحيات الأدوار",
      "View Users": "الاطلاع على المستخدمين",
      "Manage Roles": "إدارة الأدوار",
      "Manage Users": "إدارة المستخدمين",
      "Assign Roles": "تحديد الأدوار",
      "View Roles": "الاطلاع على الصلاحيات",
      "Permission to view other users account details":
          "صلاحية لعرض تفاصيل حساب المستخدمين الآخرين",
      "Permission to create,  modify other users account details":
          "صلاحية لإنشاء وتعديل تفاصيل حساب المستخدمين الآخرين",
      "Permission to assign roles to users": "صلاحية لتعيين الأدوار للمستخدمين",
      "Permission to view available roles": "صلاحية لعرض الأدوار المتاحة",
      "Permission to create, delete and modify roles":
          "صلاحية لإنشاء الأدوار وحذفها وتعديلها",
      "Company Permissions": "صلاحيات الشركات",
      "View Companies": "الاطلاع على الشركات",
      "Manage Companies": "إدراة الشركات",
      "Permission to view companies": "صلاحية لعرض الشركات",
      "Permission to create, delete and modify companies":
          "صلاحية إنشاء، حذف، وتعديل الشركات",
      "Tax Permissions": "صلاحيات الضرائب",
      "View Taxes": "الاطلاع على الضرائب",
      "Manage Taxes": "إدارة الضرائب",
      "Permission to view taxes": "صلاحية الاطلاع على الضرائب",
      "Permission to create, delete and modify taxes":
          "صلاحية إنشاء، حذف، وتعديل الضرائب",
      "Branch Permissions": "صلاحيات الفروع",
      "View Branches": "الاطلاع على الفروع",
      "Manage Branches": "إدارة الفروع",
      "Permission to view branches": "صلاحية الاطلاع على الفروع",
      "Permission to create, delete and modify branches":
          "صلاحية إنشاء، حذف، وتعديل الفروع",
      "Region Permissions": "صلاحيات المناطق",
      "View Regions": "الاطلاع على المناطق",
      "Manage Regions": "إدارة المناطق",
      "Permission to view regions": "صلاحية الاطلاع على المناطق",
      "Permission to create, delete and modify regions":
          "صلاحية إنشاء، حذف، وتعديل المناطق",
      "Neighborhood Permissions": "صلاحيات الأحياء",
      "View Neighborhoods": "الاطلاع على الأحياء",
      "Manage Neighborhoods": "إدارة الأحياء",
      "Permission to view neighborhoods": "صلاحية الاطلاع على الأحياء",
      "Permission to create, delete and modify neighborhoods":
          "صلاحية إنشاء، حذف، وتعديل الأحياء",
      "Clients Permissions": "صلاحيات العملاء",
      "View Customers": "الاطلاع على العملاء",
      "Manage Customers": "إدارة العملاء",
      "Permission to view customers": "صلاحية الاطلاع على العملاء",
      "Permission to create, delete and modify customers":
          "صلاحية إنشاء، حذف، وتعديل العملاء",
      "Coupon Permissions": "صلاحيات الكوبونات",
      "View Coupons": "الاطلاع على الكوبونات",
      "Manage Coupons": "إدارة الكوبونات",
      "Permission to view coupons": "صلاحية الاطلاع على الكوبونات",
      "Permission to create, delete and modify coupons":
          "صلاحية إنشاء، حذف، وتعديل الكوبونات",
      "Reservation Permissions": "صلاحيات الحجوزات",
      "View Reservations": "الاطلاع على الحجوزات",
      "Manage Reservations": "إدارة الحجوزات",
      "Permission to view reservations": "صلاحية الاطلاع على الحجوزات",
      "Permission to create, delete and modify reservations":
          "صلاحية إنشاء، حذف، وتعديل الحجوزات",
      "Seasonal Offer Permissions": "صلاحيات العروض الموسمية",
      "View Seasonal Offers": "الاطلاع على العروض الموسمية",
      "Manage Seasonal Offers": "إدارة العروض الموسمية",
      "Permission to view seasonal offers":
          "صلاحية الاطلاع على العروض الموسمية",
      "Permission to create, delete and modify seasonal offers":
          "صلاحية إنشاء، حذف، وتعديل العروض الموسمية",
      "Paid Offer Permissions": "صلاحيات العروض المدفوعة",
      "View Paid Offers": "الاطلاع على العروض المدفوعة",
      "Manage Paid Offers": "إدارة العروض المدفوعة",
      "Permission to view paid offers": "صلاحية الاطلاع على العروض المدفوعة",
      "Permission to create, delete and modify paid offers":
          "صلاحية إنشاء، حذف، وتعديل العروض المدفوعة",
      "Product Permissions": "صلاحيات المنتجات",
      "View Products": "الاطلاع على المنتجات",
      "Manage Products": "إدارة المنتجات",
      "Permission to view products": "صلاحية الاطلاع على المنتجات",
      "Permission to create, delete and modify products":
          "صلاحية إنشاء، حذف، وتعديل المنتجات",
      "Service Permissions": "صلاحيات المشاريع",
      "View Services": "الاطلاع على المشاريع",
      "Manage Services": "إدارة المشاريع",
      "Permission to view services": "صلاحية الاطلاع على المشاريع",
      "Permission to create, delete and modify services":
          "صلاحية إنشاء، حذف، وتعديل المشاريع",
      "Daily schedule": "الجدول اليومي",
      "Reservations list": "قائمة الحجوزات",
      "Available appointments": "المواعيد المتاحة",
      "User management": "إدارة المستخدمين",
      "Reports": "تقارير",
      "Region reports": "تقرير المناطق",
      "Service reports": "تقرير المشاريع",
      "Worker reports": "تقرير المحاسبين",
      "Product reports": "تقرير المنتجات",
      "Customer reports": "تقرير العملاء",
      "Driver reports": "تقرير السائقين",
      "Employee reports": "تقرير الموظفين",
      "Offer reports": "تقرير العروض",
      "Worker": "محاسب",
      "Driver": "سائق",
      "Other": "أخرى",
      "Job": "الوظيفة",
      "Invalid url": "رابط غير صالح",
      "Gift cards": "كروت الهدايا",
      "Sender": "المرسل",
      "Recipient": "المرسل إليه",
      "Export date": "تاريخ التصدير",
      "End date": "تاريخ الانتهاء",
      "Gift Cards Permissions": "صلاحيات كروت الهدايا",
      "view gift cards": "الاطلاع على كروت الهدايا",
      "manage gift cards": "إدارة كروت الهدايا",
      "Permission to view gift cards": "صلاحية لعرض كروت الهدايا",
      "Permission to manage gift cards": "صلاحية لإدارة كروت الهدايا",
      "Coupon owner": "صاحب الكوبون",
      "UserAccount": "حساب المستخدم",
      "Account": "حسابي",
      "My account": "حسابي",
      "Manage account": "إدارة الحساب",
      "Username is required": "اسم المستخدم مطلوب",
      "Password is required": "كلمة السر مطلوبة",
      "Sign in": "تسجيل الدخول",
      "Enter your registered email":
          "قم بإدخال بريدك الإلكتروني المسجل في النظام",
      "Forgot password": "نسيت كلمة السر",
      "?": "؟",
      "Back": "رجوع",
      "Submit": "تأكيد",
      "New password": "كلمة سر جديدة:",
      "Password must be alphanumeric and at least 8 characters":
          "يجب أن تحتوي كلمة السر على أحرف وأرقام ورموز ولا تقل عن 8",
      "Confirm password": "تأكيد كلمة السر:",
      "Confirm password is": "تأكيد كلمة السر",
      "Email is": "البريد الإلكتروني",
      "Password is": "كلمة السر",
      "Password and confirm password does not match":
          "كلمتا السر غير متطابقتين",
      "Reset password": "إعادة تعيين كلمة السر",
      "Export": "تصدير",
      "Special coupons": "كوبونات خاصة",
      "PaidOffer": "عروض مدفوعة",
      "SeasonalOffer": "عروض موسمية",
      "SpecialCoupons": "كوبونات خاصة",
      "Coupon type": "نوع الكوبون",
      "Without coupon": "بدون كوبون",
      "Total of services price": "إجمالي سعر المشاريع",
      "Total of reservation price after discount":
          "إجمالي سعر الحجز بعد تطبيق الكوبون",
      "Total of reservation price": "إجمالي سعر الحجز",
      "Total of products price": "إجمالي سعر المنتجات",
      "Total of services": "عدد المشاريع",
      "Total of products": "عدد المنتجات",
      "Total of customers": "عدد العملاء",
      "Total of reservations": "عدد الحجوزات",
      "manage app settings": "تغيير إعدادات النظام",
      "App Settings Permissions": "صلاحيات إعدادات النظام",
      "Permission to manage app settings": "صلاحية تعديل إعدادات النظام",
      "Customer name": "اسم العميل",
      "Service period": "مدة المشروع",
      "Invoice no": "رقم الفاتورة",
      "Commercial registry": "السجل التجاري",
      "Tax number": "الرقم الضريبي",
      "Send": "إرسال",
      "Print": "طباعة",
      "From": "من",
      "To": "إلى",
      "Search keyword": "عبارة البحث",
      "Edit reservation": "تعديل الحجز",
      "Products number": "عدد المنتجات",
      "Services count": "عدد المشاريع",
      "Reservations count": "عدد الحجوزات",
      "Laborers count": "عدد المحاسبين",
      "Drivers count": "عدد السائقين",
      "Products count": "عدد المنتجات",
      "Laborer": "المحاسب",
      "Laborers reports": "تقرير المحاسبين",
      "Laborers report": "تقرير المحاسبين",
      "Prices total of reservations": "إجمالي مبلغ الحجوزات",
      "Products report": "تقرير المنتجات",
      "Total of used products": "عدد المنتجات المستهلكة",
      "Total prices of used products": "إجمالي مبلغ المنتجات المستهلكة",
      "Services report": "تقرير المشاريع",
      "Total prices of used services": "إجمالي مبلغ المشاريع المقدمة",
      "Total of used services": "إجمالي المشاريع المقدمة",
      "Customers report": "تقرير العملاء",
      "Employees report": "تقرير الموظفين",
      "Units": "الوحدات",
      "Today reservations": "حجوزات اليوم",
      "Location": "الموقع",
      "No data found": "لا توجد بيانات لعرضها",
      "Totals": "إجمالي",
      "Quantity": "الكمية",
      "Discount": "خصم",
      "Laborers": "المحاسبين",
      "No matching search found": "لا توجد نتائج للبحث",
      "Session Restored": "تم استعادة الجلسة",
      "Please try your last operation again": "حاول إعادة آخر عملية قمت بها",
      "PM": "م",
      "AM": "ص",
      "Refresh": "تحديث",
      "Save preferences": "حفظ التفضيلات",
      "Session expired": "انتهت الجلسة",
      "Phone": "رقم الجوال",
      "Sales system": "نظام الصيانة",
      "Reset preferences": "إعادة تعيين التفضيلات",
      "Next page": "التالي",
      "Previous page": "السابق",
      "First page": "الصفحة الأولى",
      "Last page": "الصفحة الأخيرة",
      "of": "من",
      "Items per page": "عدد العناصر لكل الصفحة",
      "Invalid code": "رمز التفعيل غير صحيح",
      "Not found": "لا يوجد",
      "General settings": "إعدادات عامة",
      "Mail settings": "إعدادات البريد الإلكتروني",
      "Logo": "الشعار",
      "Host": "المضيف",
      "Port": "المنفذ",
      "Prices total of services": "إجمالي سعر المشاريع",
      "Prices total of products": "إجمالي سعر المنتجات",
      "Exist before": "موجود مسبقا",
      "Manage products": "إدارة المنتجات",
      "Items per page:": "عدد الصفوف في الصفحة",
      "Total price": "إجمالي السعر",
      "Manage stocks": "إدارة المخازن",
      "Created on": "تاريخ الإضافة",
      "Creator name": "أنشأ بواسطة",
      "Actions": "إجراءات",
      "Total quantity": "إجمالي المنتجات",
      "Stock": "المستودع",
      "Stocks": "المستودع",
      "New stock": "مستودع جديد",
      "Stock name": "مسمى المستودع",
      "Purchase invoices": "فواتير الشراء",
      "Expiration date": "تاريخ الانتهاء",
      "Buying price": "سعر البيع",
      "Selling price": "سعر الشراء",
      "Attempting login": "جاري الدخول",
      "Invoice number": "رقم الفاتورة",
      "Invoice date": "تاريخ الفاتورة",
      "Supplier": "المورد",
      "Stock has expired products": "هناك منتجات على وشك الانتهاء في المخزون",
      "Warn": "تحذير",
      "Stock reports": "تقارير المخازن",
      "Projects": "المشاريع",
      "Project name": "اسم المشروع",
      "Project english name": "اسم المشروع بالإنجليزي",
      "Edit project": "تعديل المشروع",
      "Identity no": "رقم الهوية",
      "Customer management": "إدارة العملاء",
      "Customer visits": "زيارات العملاء",
      "Investors": "المستثمرون",
      "Reservation agreements": "اتفاقيات الحجوزات",
      "Visit date": "تاريخ الزيارة",
      "Date and time": "التاريخ والوقت",
      "SupportedBank": "بنك مدعوم",
      "UnsupportedBank": "بنك غير مدعوم",
      "NotSuitable": "بنك غر مدعوم",
      "Visit no": "رقم الزيارة",
      "Project": "المشروع",
      "Contract no": "رقم العقد",
      "Reservation no": "رقم الحجز",
      "Contract signer name": "اسم موقع العقد",
      "Contract title": "عنوان العقد",
      "Agent identity": "هوية الوكيل",
      "Contracts": "عقود المبايعة",
      "Agency no": "رقم الوكالة",
      "Changes was saved successfully": "تم حفظ التغييرات بنجاح",
      "Unit receiver name": "اسم المستلم",
      "Unit receivers": "استلام الوحدات",
      "Receiver name": "اسم المستلم",
      "Contract Permissions": "صلاحيات العقود",
      "Customer visit permissions": "صلاحيات زيارات العملاء",
      "Unit receiving permissions": "صلاحيات استلام الوحدات",
      "Investor Permissions": "صلاحيات المستثمرين",
      "Project Permissions": "صلاحيات المشاريع",
      "View Investors": "الاطلاع على المستثمرين",
      "Manage Investors": "إدارة المستثمرين",
      "View Contracts": "الاطلاع على العقود",
      "Manage Contracts": "إدارة العقود",
      "View Customer visit": "الاطلاع على زيارات العملاء",
      "Manage Customer visit": "إدارة زيارات العملاء",
      "View Unit receiving": "الاطلاع على استلام الوحدات",
      "Manage Unit receiving": "إدارة استلام الوحدات",
      "View Projects": "الاطلاع على المشاريع",
      "Manage Projects": "إدارة المشاريع",
      "Management": "إدارة",
      "Operation issues permissions": "صلاحيات التشغيل والصيانة",
      "View operation issues": "الاطلاع على تقارير التشغيل والصيانة",
      "Manage operation issues": "إدارة تقارير التشغيل والصيانة",
      "Issue type": "نوع المشكلة",
      "Maintenance type": "نوع الصيانة",
      "Resources price": "سعر الموارد",
      "Unit name": "اسم الوحدة",
      "Operation issue criteria": "معيار التقرير",
      "Criteria": "المعيار",
      "Operation issues": "التشغيل والصيانة",
      "Unit": "الوحدة",
      "Choose a date and time": "حدد التاريخ والوقت",
      "Choose a date": "اختر التاريخ",
      "Our clients": "عملاؤنا",
      "Visitor messages": "رسائل الزوار",
      "Message details": "تفاصيل الرسالة",
      "About us": "من نحن",
      "Brief": "نبذة",
      "Facebook": "فيسبوك",
      "Instagram": "إنستقرام",
      "Tiktok": "تكتوك",
      "Whatsapp": "واتسأب",
      "Twitter": "تويتر",
      "Snapchat": "سناب شات",
      "Welcome text": "نص ترحيبي",
      "Sliders": "صور العرض الرئيسي",
      "Banner": "الصورة",
      "Upload file": "رفع الملف",
      "Maintenance request": "طلب صيانة",
      "Please fill in the following details":
          "قم من فضلك بتعبئة الحقول التالية",
      "Example": "مثال",
      "Building": "المبنى",
      "Unit no": "رقم الوحدة",
      "Visit time": "وقت الزيارة",
      "First period from 10 AM to 2 PM": "الفترة الأولى ١٠ص - ٢م",
      "Second period from 3 PM to 6 PM": "الفترة الثانية ٣م - ٦م",
      "Issue photo": "صورة المشكلة",
      "Attach photo": "إرفاق صورة",
      "Issue details": "تفاصيل المشكلة",
      "Maintenance details": "تفاصيل الصيانة",
      "Enter phone number in form of 05xxxxxxxx":
          "أدخل رقم الجوال بالصيغة 05xxxxxxxx",
      "File upload error": "خطأ في تحميل الملف",
      "Only images or pdf can be uploaded":
          "فقط ملفات الصور أو البي دي إف يمكنك تحميلها",
      "File size must be less than 100 MB":
          "يجب أن لا يزيد حجم الملف عن 100 ميجا بايت",
      "Unable to upload file to the server.": "لا يمكن تحميل الملف.",
      "Errors": "الأخطاء",
      "FileSize": "حجم الملف",
      "FileType": "نوع الملف",
      "Enter activation code":
          "أدخل الرمز المرسل على جوالك أو بريدك الإلكتروني",
      "One or more errors occurred while saving your changes":
          "حدث خطأ ما أثناء حفظ التغييرات",
      "Activation code sent": "تم إرسال رمز التفعيل",
      "We have sent activation code to your phone":
          "تم إرسال رمز التفعيل على رقم جوالك",
      "Send error": "خطأ في الإرسال",
      "Unable to send code": "لم نتمكن من إرسال الرمز",
      "Unable to send": "فشل الإرسال",
      "Error": "خطأ",
      "error": "خطأ",
      "Your order was sent successfully": "تم إرسال الطلب بنجاح",
      "Quick sign in": "دخول سريع",
      "Enter your registered phone": "أدخل رقم الجوال",
      "Code sent": "تم إرسال الرمز",
      "We have sent code to your phone": "لقد قمنا بإرسال الرمز على جوالك",
      "Questionnaires": "الاستبيانات",
      "Questionnaires list": "قائمة الاستبيانات",
      "Choices": "الاختيارات",
      "Questions": "الأسئلة",
      "Your request has been completed successfully, please rate the service provided":
          "تم الانتهاء من تنفيذ طلبكم بنجاح، نرجو منكم تقييم الخدمة المقدمة",
      "Thank you": "شكرا لك",
      "You have submit this questionnaire before":
          "لقد قمت بتقييم هذا الاستبيان من قبل",
      "NotFound": "الصفحة غير موجودة",
      "Submissions count": "عدد الردود",
      "Unable to load data from server.":
          "غير قادر على تحميل البيانات من الخادم",
      "Maintenance requests permissions": "صلاحيات طلبات الصيانة",
      "Manage maintenance requests": "إدارة طلبات الصيانة",
      "FirstPeriod": "الفترة الأولى",
      "SecondPeriod": "الفترة الثانية",
      "Building code": "رمز المبنى",
      "Project issue type": "نوع المشكلة",
      "Maintenance requests": "طلبات الصيانة",
      "Client": "عميل",
      "Other incomes permissions": "مدخرات أخرى",
      "Manage other incomes": "إدارة المدخرات الأخرى",
      "Other incomes": "مدخرات أخرى",
      "Plumbing": "سباكة",
      "Electricity": "كهرباء",
      "AirConditioning": "تكييف",
      "Paint": "طلاء",
      "The client": "العميل",
      "The service": "الخدمة",
      "Maintenance official": "مسؤول صيانة",
      "MaintenanceOfficial": "مسؤول صيانة",
      "View": "عرض",
      "Action": "إجراء",
      "Transfer": "تحويل",
      "Start": "بدء",
      "Home": "الرئيسية",
      "The project": "المشروع",
      "MaintenanceTechnician": "فني صيانة",
      "The maintenance technician": "فني الصيانة",
      "Sent": "تم الإرسال",
      "Transfered": "محولة",
      "InProgress": "جاري العمل",
      "Closed": "مغلق",
      "Hold": "تأجيل",
      "Successfully done": "تمت العملية بنجاح",
      "Are you sure?": "هل أنت متأكد من هذا الإجراء؟",
      "StartToPerformTask": "بدء",
      "Follow up": "متابعة",
      "Hold reason": "سبب التأجيل",
      "Start to perform task": "بدء",
      "Unclose": "تأجيل",
      "Submittion code will be sent to the client phone":
          "سيتم إرسال رمز تحت تحقق إلى جوال العميل",
      "Code sent to the client": "تم إرسال رمز التحقق إلى العميل",
      "Please submit it": "فضلا قم بإدخاله",
      "Hold to date": "يؤجل إلى",
      "Hold reasons": "أسباب التأجيل",
      "Start date": "تاريخ البدء",
      "Created date": "أضيف بتاريخ",
      "Second party": "الطرف الثاني",
      "Contract body": "نص العقد",
      "Save as draft": "حفظ كمسودة",
      "Password must be alphanumeric and at least 4 characters":
          "كلمة السر يجب أن لاتقل عن 4 رموز",
      "Draft": "مسودة",
      "Approved": "معتمد",
      "Service details": "تفاصيل الخدمة",
      "Hide contract": "إخفاء العقد",
      "The contract": "العقد",
      "Contract": "عقد",
      "Accept": "قبول",
      "Ok": "حسنا",
      "Agree": "موافق",
      "Accepted done": "تمت الموافقة",
      "Accepting contract": "الموافقة على العقد",
      "Are you sure from accepting contract":
          "هل أنت متأكد من الموافة على بنود العقد",
      "Invalid phone number or code": "رقم الجوال أو الرمز غير صحيح",
      "Attempting to send code...": "جاري إرسال الكود",
      "An error occurred, please try again later": "حدث خطأ ما، حاول مرة أخرى",
      "There is no contract": "ليس لديك عقد",
      "Common part contract": "عقد الأجزاء المشتركة",
      "Contract has been accepted": "تمت الموافقة على العقد",
      "User already exist": "المستخدم مسجل مسبقا",
      "New user": "مستخدم جديد",
      "Service type": "نوع الخدمة",
      "Cant send message to client": "لا يمكن إرسال رسالة للعميل",
      "RequestSent": "تم إرسال الطلب",
      "RequestTransfered": "تم قبول الطلب",
      "RequestInProgress": "جاري معالجة الطلب",
      "RequestClosed": "تم إقفال الطلب",
      "RequestHold": "تم تأجيل الطلب",
      "SendRequest": "إرسال",
      "TransferRequest": "تحويل",
      "StartToPerformTaskRequest": "بدء",
      "CloseRequest": "إغلاق",
      "UncloseRequest": "تأجيل",
      "Service name": "اسم الخدمة",
      "Current day": "اليوم",
      "Current week": "هذا الأسبوع",
      "Current month": "هذا الشهر",
      "Custom": "مخصص",
      "Search by request no, unit no...": "ابحث برقم الطلب...",
      "RequestFinish": "منتهي",
      "FinishRequest": "إنهاء",
      "NoReplyFromClient":
          "عزيزي العميل تواصلنا معكم أكثر من مرة بخصوص طلبكم رقم {{number}} ولم يتم الرد، وتم تأجيل موعد الصيانة إلى تاريخ {{date}}",
      "HoldByClient":
          " عزيزي العميل بناء على طلبكم رقم {{number}} تم تأجيل موعد الصيانة إلى تاريخ {{date}}",
      "Reservation invalid in this date": "لا يمكن الحجز في هذا التاريخ",
      "Maintenance request form": "نموذج طلب صيانة",
      "Service request form": "نموذج طلب خدمة",
      "Soon": "قريبا",
      "Prices": "تسعيرات",
      "Paid services": "الخدمات المدفوعة",
      "Submission successfully done": "تم التقييم بنجاح",
      "Changes to your User Profile was saved successfully":
          "تم حفظ بيانات البروفايل بنجاح",
      "Add attachments": "إضافة مرفقات",
      "Attachments": "المرفقات",
      "Evaluate cleanliness and facilities": "تقييم النظافة والمرافق",
      "New assessment": "تقييم جديد",
      "Edit assessment": "تعديل التقييم",
      "Manage assessments": "إدارة التقييمات",
      "Poor": "ضعيف",
      "Fair": "متوسط",
      "Good": "جيد",
      "VeryGood": "جيد جدا",
      "Excellent": "ممتاز",
      "Visit date and time": "تاريخ ووقت الزيارة",
      "Assessment elements": "عناصر التقييم",
      "Upload photo": "رفع صورة",
      "Upload files": "رفع ملفات",
      "Others": "أخرى",
      "Confirm the deletion": "تأكيد الحذف",
      "Confirm": "تأكيد",
      "You cannot make reservations during this period":
          "لا يمكنك الحجز في هذه الفترة",
      "Questionnaires submissions": "تقييمات العملاء",
      "Request number": "رقم الطلب",
      "MismatchFromClient":
          "عزيزي العميل بناء على المحادثة معكم تم تأجيل موعد الصيانة لطلبكم رقم {{number}} إلى تاريخ {{date}}",
      "Code submission has been sent before": "تم إرسال كود التأكيد من قبل",
      "From 8:00pm to 1:30am": "من ٨:٠٠ م حتى ١:٣٠ص",
      "Manage invoices": "إدارة الفواتير",
      "New invoice": "فاتورة جديدة",
      "ُEdit invoice": "تعديل فاتورة",
      "Invoices": "الفواتير",
      "Client name in invoice": "اسم العميل في الفاتورة",
      "Amount in letters": "المبلغ كتابة",
      "Days off": "أيام الإجازات",
      "Of": "من",
      "Edit invoice": "تعديل الفاتورة",
      "My requests": "طلباتي",
      "Manage requests": "إدارة الطلبات",
      "Today requests": "طلبات اليوم",
      "Closed requests": "طلبات مقفلة",
      "The technician is on his way to you": "الفني في طريقه إليك",
      "The technician": "الفني",
      "New request": "طلب جديد",
      "New paid service": "طلب خدمة مدفوعة",
      "Services management": "إدارة الخدمات",
      "Need maintenance": "طلب صيانة",
      "More": "المزيد",
      "Common parts": "الأجزاء المشتركة",
      "Request date": "تاريخ الطلب",
      "Must not be greater than ... characters":
          "يجب أن لا يزيد طول النص عن {{number}} رمز",
      "View other incomes": "الاطلاع على المدخرات الأخرى",
      "Facade": "واجهة المبنى",
      "Basement": "البدروم",
      "FirstFloor": "الدور الأول",
      "SecondFloor": "الدور الثاني",
      "ThirdFloor": "الدور الثالث",
      "FirstDeck": "السطح الأول",
      "UpperDeck": "السطح العلوي",
      "Maintenance location": "موقع الصيانة",
      "Init done": "إقفال",
      "Manage": "إدارة",
      "Manage all": "إدارة الكل",
      "Common parts permissions": "صلاحيات الأجزاء المشتركة",
      "Transferred": "تحويل",
      "InitDone": "إقفال",
      "Inside": "داخل",
      "Outside": "خارج",
      "Type": "النوع",
      "Previous requests": "الطلبات السابقة",
      "Project maintenance": "صيانة المشاريع",
      "Prices permissions": "صلاحيات التسعيرات",
      "New Requests": "طلبات جديدة",
      "Partially Closed": "مغلقة جزئيا",
      "Closed Requests": "طلبات مغلقة",
      "Transferred Requests": "طلبات محولة",
      "Instructions": "تعليمات",
      "Close without code": "إغلاق بدون إرسال كود",
      "Holded to date": "مؤجل إلى",
      "This account has been disabled": "هذا الحساب معطل",
      "Sorry!": "عذرا!",
      "We apologize to you, dear customer, that the project is out of warranty. We also apologize for the paid maintenance and we will reopen the paid maintenance as soon as possible.":
          "نعتذر منك عزيزي العميل المشروع خارج الضمان ، ونعتذر كذلك عن الصيانة المدفوعة وسنعاود فتح الصيانة المدفوعة في أقرب وقت .",
      "updated date": "آخر تحديث",
      "Dont send assesments message": "لا تقم بإرسال رسالة التقييم للعميل",
      "Urgent": "عاجل",
      "New urgent request": "طلب طارئ جديد",
      "Urgent requests": "الطلبات العاجلة",
      "Urgent type": "نوع الطارئ",
      "System settings": "إعدادات النظام",
      "Urgent phone": "جوال الطوارئ",
      "Char": "حرف",
      "Count of ponuses": "النقاط المكتسبة",
      "Count of penalties": "النقاط المفقودة",
      "Add points": "إضافة نقاط",
      "Cut points": "خصم نقاط",
      "Cut": "خصم",
      "Points count": "عدد النقاط",
      "Staff points": "نقاط الموظفين",
      "Beginning": "البداية",
      "End": "النهاية",
      "Points of": "نقاط",
      "Points management": "إدارة النقاط",
      "Totals report": "تقرير إجمالي",
      "Detailed Report": "تقرير مفصل",
      "Count of points": "عدد النقاط",
      "RequestInitClosed": "إغلاق مبدئي",
      "Initial close": "إغلاق مبدئي",
      "Edit stock": "تعديل المستودع",
      "Cost title": "مسمى التكلفة",
      "Cost": "التكلفة",
      "Overall rate": "المعدل العام",
      "My points": "نقاطي",
      "Future requests": "طلبات مستقبلية",
      "Tomorrow's requests": "طلبات الغد",
      "Total report": "تقرير إجمالي",
      "By the technician": "بواسطة الفني",
      "By creator of the request": "بواسطة منشئ الطلب",
      "Deleting": "جاري الحذف",
      "Entrepreneurs Permissions": "صلاحيات المقاولين",
      "Entrepreneurs": "المقاولون",
      "Projects management": "إدارة المشاريع",
      "Complaint permissions": "صلاحيات الشكاوى ",
      "Complaints": "الشكاوى",
      "New complaint": "شكوى جديدة",
      "Complaints management": "إدارة الشكاوى",
      "ComplaintSent": "جديد",
      "ComplaintTransfered": "محولة",
      "ComplaintInitClosed": "مغلقة جزئيا",
      "ComplaintClosed": "مغلقة",
      "New Complaints": "شكاوى جديدة",
      "Transfered Complaints": "شكاوى محولة",
      "Colsed Complaints": "شكاوى مغلقة",
      "Transferred Complaints": "شكاوى محولة",
      "Closed Complaints": "شكاوى مغلقة",
      "Complaint number": "رقم الشكوى",
      "PDF": "بي دي إف",
      "Excel": "إكسل",
      "Question": "السؤال",
      "Guarantees": "الضمانات",
      "Guarantees Permissions": "صلاحيات الضمانات",
      "Label": "تسمية",
      "Attachment": "مرفق",
      "File": "ملف",
      "Upload": "رفع",
      "Stocks management": "إدارة المستودعات",
      "Products Permissions": "صلاحيات المنتجات",
      "Manage Categories": "إدارة الأصناف",
      "Product categories": "أصناف المنتجات",
      "Stocks Permissions": "صلاحيات المستودع",
      "Category": "التصنيف",
      "Suspend": "تعليق",
      "Suspended": "تعليق",
      "Subtract": "إنقاص",
      "Riyals": "ريال",
      "Quantity available": " الكمية المتوفرة",
      "The quantity to be increased or decreased":
          "الكمية المطلوب زيادتها أو إنقاصها",
      "View Clients": "الاطلاع على العملاء",
      "Quality Requests permissions": "صلاحيات طلبات الاستلام من الجودة",
      "Return": "إرجاح",
      "Quality": "الجودة",
      "Requests management": "إدارة الطلبات",
      "Civil": "مدني",
      "Architectural": "معماري",
      "Mechanics": "ميكانيكي",
      "Classification": "التصنيف",
      "New requests": "طلبات جديدة",
      "Returned": "يوجد ملاحظات",
      "Accepted": "مقبول",
      "Manage Project Files": "إدارة ملفات المشروع",
      "View Project Files": "الاطلاع على ملفات المشروع",
      "Project Files": "ملفات المشروع",
      "Plans": "المخططات",
      "WorkStages": "مراحل العمل",
      "MaterialReconstruction": "مواد البناء",
      "Project issues": "مشاكل المشاريع",
      "New issue": "مشكلة جديدة",
      "Re sent": "إعادة إرسال",
      "Re send": "إعادة إرسال",
      "ReSend": "إعادة إرسال",
      "ReSent": "إعادة إرسال",
      "There is no files found": "لا توجد ملفات",
      "Entrepreneur issue permissions": "مشاكل المشاريع المتعلقة بالمقاولين",
      "Project issues management": "إدارة مشاكل المشاريع",
      "The entrepreneur": "المقاول",
      "Issue number": "رقم المشكلة",
      "New Issues": "مشاكل جديدة",
      "Solved Issues": "مشاكل تم حلها",
      "EntrepreneurIssueSent": "مرسلة",
      "EntrepreneurIssueSolved": "تم الحل",
      "Solve": "حل",
      "Select": "تحديد",
      "Select all": "اختر الكل",
      "Clear search": "إلغاء البحث",
      "Zones Permissions": "صلاحيات المناطق",
      "Shifts Permissions": "صلاحيات الورديات",
      "User points permissions": "صلاحيات نقاط الموظفين",
      "Evaluate cleanliness and facilities permissions": "صلاحيات التقييمات",
      "Fingerprint": "البصمة",
      "Shifts": "الورديات",
      "Zones": "المناطق",
      "Zone name": "اسم المنطقة",
      "Latitude": "خط العرض",
      "Longitude": "خط الطول",
      "Radius in meter": "القطر بالمتر",
      "Start time": "وقت البدء",
      "End time": "وقت الانتهاء",
      "Flexible minutes": "الدقائق المرنة",
      "Shift name": "مسمى الوردية",
      "Start time to check in": "وقت بدء بصمة الدخول",
      "End time to check in": "وقت انتهاء بصمة الدخول",
      "Start time to check out": "وقت بدء بصمة الانصراف",
      "End time to check out": "وقت انتهاء بصمة الانصراف",
      "Forget a fingerprint": "نسيان بصمة",
      "Is part time": "نصف دوام",
      "When this option is enabled, attendance/absence is counted in half-day reports":
          "عند تفعيل هذا الخيار، يتم احتساب الحضور/الغياب في التقارير نصف يوم",
      "Days of work": "أيام العمل",
      "You cannot choose from more than one category":
          "لا يمكنك الاختيار من أكثر من تصنيف بنفس الطلب",
      "Only images or pdf or videos can be uploaded":
          "فقط ملفات الصور أو البي دي إف أو الفيديوهات يمكن تحميلها",
      "history report": "تقرير البصمة مفصل",
      "history report region": "تقرير البصمة مجمع",
      "The monthly average of late and leaving minutes":
          "المعدل الشهري لدقائق التأخر والانصراف",
      "General report": "تقرير مجمل",
      "Absence report": "تقرير الغياب",
      "My fingerprint": "بصمتي",
      "No widgets": "لم يتم عرض أية أدوات. اذهب إلى",
      "to configure available widgets": "لتكوين الأدوات المتاحة",
      "Page not found": "الصفحة التي تبحث عنها غير موجودة",
      "Back to home": "العودة إلى لوحة الإستقبال",
      "User preferences": "خيارات المستخدم",
      "User departments": "أقسام المستخدم",
      "Role management": "إدارة الأدوار",
      "Reload preferences": "إعادة تحميل التفضيلات:",
      "Select the default page to navigate to on login":
          "حدد الصفحة الافتراضية للانتقال إلى تسجيل الدخول",
      "Dashboard statistics": "إحصائيات لوحة التحكم:",
      "Show graph widget on the dashboard":
          "عرض الرسم البياني على لوحة القيادة",
      "Dashboard notifications": "إشعارات لوحة التحكم:",
      "Show application notifications on the dashboard":
          "عرض إشعارات التطبيق على لوحة التحكم",
      "Dashboard todo": "لوحة التحكم للواجبات:",
      "Shows todo widget on the dashboard":
          "يظهر الوحة  للواجبات على لوحة القيادة",
      "Dashboard banner": "بنر لوحة التحكم:",
      "Show banner information widget on the dashboard":
          "عرض معلومات البنر على لوحة القيادة",
      "Reset default": "إرجاع الافتراضي",
      "Set default": "تعيين كافتراضي",
      "Edit user": "تعديل المستخدم \"{{name}}\"",
      "User name is required (minimum of 2 and maximum of 200 characters)":
          "(مطلوب اسم المستخدم (الحد الأدنى من 2 والحد الأقصى 200 حرفا",
      "Current password is required": "كلمة السر الحالية مطلوبة",
      "Change password": "تغيير كلمة السر",
      "Current password": "كلمة السر الحالية:",
      "New password is required": "الحد الأدنى من 6 أحرف) مطلوب كلمة سر)",
      "Confirmation password is required": "مطلوب كلمة سر التأكيد",
      "New password and confirmation password do not match":
          "لا تتطابق كلمة السر الجديدة وكلمة سر التأكيد",
      "Role is required": "الدور مطلوب",
      "Email address is required (maximum of 200 characters)":
          "عنوان البريد الإلكتروني مطلوب (بحد أقصى 200 حرف)",
      "Invalid email": "البريد الإلكتروني المحدد غير صالح",
      "Phone number": "رقم الجوال",
      "New role": "دور جديد",
      "Role details": "تفاصيل الدور \"{{name}}\"",
      "Edit role": "  تحرير الدور\"{{name}}\"",
      "Role name is required (minimum of 2 and maximum of 200 characters)":
          "(اسم الدور مطلوب (بحد أدنى 2 و 200 حرف كحد أقصى",
      "Select none": "لا تختر شيء",
      "Hide completed": "إخفاء المكتمل",
      "New task": "مهمة جديدة",
      "Task name required": "مطلوب اسم المهمة",
      "Product category name": "تصنيف المنتج",
      "Complete tasks": "المهام المنتهية",
      "Ongoing tasks": "المهام الجارية",
      "Next tasks": "المهام القادمة",
      "Start date is required": "وقت بدء المهمة مطلوب",
      "Days ranking": "ترتيب الأيام حسب ضغط العمل",
      "Weekly report": "التقرير الأسبوعي",
      "Assign users to zone": "إسناد المستخدمين للمنطقة",
      "Assign users to shift": "إسناد المستخدمين للشفت",
      "Admin": "إدارة",
      "M": "د",
      "Some Important Stuff": "إحصائيات",
      "Company name": "اسم الشركة",
      "Employees total": "إجمالي عدد الموظفي",
      "Full name": "الاسم كاملا",
      "Job title": "المسمى الوظيفي",
      "Direct manager": "المدير المباشر",
      "At least 6 characters": "6 رموز على الأقل",
      "Missing Information": "مدخلات غير صحيحة أو غير مكتملة",
      "You have entered invalid or incomplete information. Please correct any errors and try again":
          "لقد أدخلت معلومات غير صالحة أو غير كاملة. يرجى تصحيح أي أخطاء والمحاولة مرة أخرى",
      "App is Loading": "جاري تحميل التطبيق",
      "New Role": "دور جديد",
      "View Company Users": "الاطلاع على مستخدمي شركتي",
      "Manage Company Users": "إدارة مستخدمي شركتي",
      "Manage All Shifts": "إدارة جميع الورديات",
      "Manage Company Shifts": "إدارة ورديات الشركة",
      "Manage All Zones": "إدارة جميع المناطق",
      "Manage Company Zones": "إدارة مناطق الشركة",
      "Companies Permissions": "صلاحيات الشركات",
      "Permission View Company Users":
          "صلاحية اطلاع على مستخدمي الشركة الخاصة بالمستخدم",
      "Permission Manage Company Users": "صلاحية اطلاع على مستخدمي الشركة",
      "Permission to create, manage and modify shifts":
          "صلاحية بإنشاء وإدارة وتعديل الورديات",
      "Permission to create, manage and modify shifts of company":
          "صلاحية لإنشاء وإدارة وتعديل ورديات الشركة",
      "Permission to create, manage and modify zones":
          "صلاحية بإنشاء وإدارة وتعديل المناطق",
      "Permission to create, manage and modify zones of company":
          "إذن بإنشاء وإدارة وتعديل مناطق الشركة",
      "Permission to create, manage and modify Companies":
          "صلاحية إنشاء وإدارة وتعديل الشركات",
      "Weekly employee reports": "تقارير الموظف الأسبوعية",
      "History report": "تقرير البصمة",
      "Employee": "الموظف",
      "Check in date": "تاريخ ووقت الدخول",
      "Minutes late": "دقائق التأخر",
      "Check out date": "تاريخ ووقت الخروج",
      "Minutes early departure": "دقائق الانصراف المبكر",
      "Minutes excuse": "دقائق الاستئذان",
      "Reset preferences to application defaults (local only)":
          "إعادة تعيين التفضيلات إلى الإعدادات الافتراضية للتطبيق (محلي فقط)",
      "Save preferences to the cloud (synchronized between devices)":
          "حفظ التفضيلات على السحابة (متزامنة بين الأجهزة)",
      "Show information banner widget on the dashboard":
          "إظهار عنصر واجهة مستخدم بنر المعلومات على لوحة الداشبورد",
      "User profile": "الملف الشخصي",
      "Defaults loaded": "تم تحميل الافتراضيات",
      "Notification error": "خطأ في الإشعارات",
      "Marking read notifications failed": "فشل وضع علامة مقروء",
      "An error occurred, please try again later.":
          "حدث خطأ ما، حاول مرة أخرى.",
      "Session for": "الجلسة الخاصة بـ",
      "restored": "تم استعادة",
      "Invalid username or password": "كلمة السر أو اسم المستخدم غير صحيح",
      "Load Error": "خطأ في التحميل",
      "Loading new notifications from the server failed!":
          "فشل تحميل إشعارات جديدة من الخادم!",
      "Attendance general report": "تقرير البصمة مجمل",
      "Absence general report": "تقرير الغياب",
      "Absent work days": "أيام الغياب",
      "Actual work days": "أيام الحضور",
      "Normal work days": "عدد أيام الدوام الفعلي",
      "Shift": "الوردية",
      "User name is": "اسم المستخدم",
      "User account": "حسابي",
      "Timezone": "المنطقة الزمنية",
      "Select timezone": "اختر المنطقة الزمنية",
      "Sign out": "تسجيل الخروج",
      "Show": "عرض",
      "Reject reasons": "أسباب الرفض",
      "Request title": "عنوان الطلب",
      "Emergency": "طارئ",
      "Standard": "قياسي",
      "Normal": "طبيعي",
      "Need": "الاحتياج",
      "Required parts": "قطع غيار مطلوبة",
      "Start on": "تاريخ البدء",
      "End on": "تاريخ الانتهاء",
      "Priority": "الأولوية",
      "Rejected": "مرفوض",
      "Visited": "تمت الزيارة",
      "VisitedAndUnderMaintenance": "تمت الزيارة وجاري الصيانة",
      "Visited and under maintenance": "تمت الزيارة وجاري الصيانة",
      "Complete": "مكتمل",
      "Save and send": "حفظ وإرسال",
      "Transform": "تحويل",
      "Reject": "رفض",
      "Transformed": "محولة",
      "Sent successfully": "تم الإرسال بنجاح",
      "title is required (minimum of 2 and maximum of 200 characters)":
          "العنوان مطلوب (بحد أدنى 2 حرف وحد أقصى 200 حرف)",
      "Request creator": "مقدم الطلب",
      "Sending": "إرسال",
      "VisitedAndSolvedInPlace": "تمت الزيارة وتم الحل في المكان",
      "VisitedAndSolvedOnline": "تمت الزيارة وتم الحل أونلاين",
      "Visited and solved in place": "تمت الزيارة وتم الحل في المكان",
      "Visited and solved Online": "تمت الزيارة وتم الحل أونلاين",
      "Transform to": "تحويل إلى",
      "Visit": "زيارة",
      "Requirement parts": "قطع غيار مطلوبة",
      "Zone": "المنطقة",
      "Creation has been completed successfully": "تمت عملية الإضافة بنجاح",
      "Edit shift": "تعديل الوردية",
      "Assign zones and shifts to user": "تحديد المنطقة والوردية لـ",
      "Assign": "إسناد",
      "Fingerprint Pro": "بصمتي",
      "Outside of zone": "خارج المنطقة",
      "Manage all maintenance requests": "إدارة  كل طلبات الصيانة",
      "View all maintenance requests": "الاطلاع على كل طلبات الصيانة",
      "Transform maintenance requests": "تحويل طلبات الصيانة",
      "Accept maintenance requests": "قبول طلبات الصيانة",
      "Reject maintenance requests": "رفض طلبات الصيانة",
      "Send maintenance requests": "إرسال طلبات الصيانة",
      "Reports permissions": "صلاحيات التقارير",
      "view reports": "الاطلاع على التقارير",
      "View maintenance requests": "الاطلاع على طلبات الصيانة",
      "Approve": "اعتماد",
      "Approved by": "اعتمد من قبل",
      "You cant send new request until approve previous":
          "لا يمكنك إرسال طلب جديد حتى تقوم بالتأكيد على الطلبات السابقة",
      "The below errors occurred while saving your changes:":
          "حدثت الأخطاء التالية عند الحفظ",
      "Visit notes": "ملاحظات الزيارة",
      "Computer and networks": "كمبيوتر وشبكات",
      "Audio and video systems": "أنظمة صوت وكاميرات",
      "ComputerAndNetworks": "كمبيوتر وشبكات",
      "AudioAndVideoSystems": "أنظمة صوت وكاميرات",
      "Requirements": "المتطلبات",
      "Proactive visits permissions": "زيارات استباقية",
      "Manage proactive visits": "إدارة الزيارات الاستباقية",
      "Manage all proactive visits": "إدارة جميع الزيارات الاستباقية",
      "View all proactive visits": "الاطلاع على كل الزيارات الاستباقية",
      "View proactive visits": "الاطلاع على الزيارات الاستباقية",
      "Proactive visits": "زيارات استباقية",
      "Department name": "المجمع",
      "The department": "القسم",
      "Out side zone times": "بصمات خارج المنطقة",
      ",": "،",
      "Update IMEI": "تعديل IMEI",
      "Delete Users": "حذف المستخدمين",
      "Permission to create, and modify other users account details":
          "صلاحية لإنشاء وتعديل تفاصيل حساب المستخدمين الآخرين",
      "Activation": "التفعيل",
      "Disabled": "معطل",
      "User status": "حالة المستخدم",
      "Proactive": "استباقية",
      "Inspection": "اعتيادية",
      "Visit type": "نوع الزيارة",
      "Visits": "الزيارات",
      "Visit schedules permissions": "صلاحيات جدولة الزيارات",
      "Manage visit schedules": "إدارة جداول الزيارات",
      "Visit schedules": "جداول الزيارات",
      "View check in region": "الاطلاع على موقع البصمة",
      "Assign zone": "تحديد المنطقة",
      "None": "بدون",
      "First": "أولا",
      "Last": "أخيرا",
      "Both": "كلاهما",
      "For employees only": "خاص بالموظفين",
      "Cant determine your location, be sure that you allow access to location":
          "لم نتمكن من تحديد موقعك الجغرافي، تأكد من صلاحية السماح للوصول إليه",
      "NoZone": "لا توجد منطقة",
      "You have no zone, or out of your allowed zones":
          "ليس لديك مناطق، أو أنك خارج المنطقة المسموح بها",
      "Exists Before": "موجود مسبقا",
      "You can not check in at this time": "لا يمكنك التبصيم في هذا الوقت",
      "OutOfShiftCheckIn": "خارج الوردية",
      "Exit": "خروج",
      "Fingerprint confirmation of exit": "تأكيد بصمة الانصراف",
      "Are you sure from exit?": "هل أنت متأكد من الانصراف؟",
      "RequestInProcessing": "جاري التنفيذ",
      "Start implementation": "بدء التنفيذ",
      "StartToProcessTaskRequest": "بدء التنفيذ",
      "Minute": "دقيقة",
      "d ": "ي ",
      "h ": "س ",
      "m ": "د ",
      "s ": "ث ",
      "Stop": "إيقاف",
      "Time spent": "إجمالي الوقت المحتسب في تنفيذ المهمة",
      "Received item": "العنصر المستلم",
      "QualityEmployee": "موظف جودة",
      "Those concerned with the request": "المعنيون بالطلب",
      "Write a reply": "أضف ردا",
      "Comments": "التعليقات",
      "Write a new comment": "كتابة تعليق جديد",
      "Comment": "تعليق",
      "Reply": "رد",
      "Replies": "الردود",
      "Basic info": "بيانات أساسية",
      "Approvals": "الاعتمادات",
      "Resume": "استئناف",
      "Maintenance items": "عناصر الصيانة",
      "Total time spent": "إجمالي وقت التنفيذ",
      "Department": "الإدارة",
      "Maintenance": "الصيانة",
      "View department users": "الاطلاع على مستخدمي القسم",
      "Manage department users": "إدارة مستخدمي القسم",
      "You do not have sufficient permissions to access this page":
          "ليس لديك الصلاحيات الكافية للوصول إلى هذه الصفحة",
      "Access denied": "ممنوع الوصول",
      "Invalid username, username should be between 3 and 20 english digits and not contains spaces and starts with character":
          "اسم المستخدم غير صالح، يجب أن يتكون اسم المستخدم من 3 إلى 20 رمزا باللغة الإنجليزية ولا يحتوي على مسافات ويبدأ بحرف ولا يحتوي على رموز خاصة",
      "Technician monthly evaluation permissions": "صلاحيات التقييمات الشهرية",
      "Monthly assessments": "التقييمات الشهرية",
      "Most closing for requests": "الأكثر إقفالا للطلبات",
      "The best and most rated by customers":
          "الأفضل والأكثر تقييما من العملاء في النظام",
      "Closing orders according to the period specified by the customer and closing the order once it is processed":
          "إقفال الطلبات حسب الفترة المحدد من العميل وإقفال الطلب حال المعالجة",
      "Good artistic appearance": "حسن مظهر الفني",
      "Most monitored observations in Technicians":
          "الأكثر رصدا للملاحظات في المشاريع",
      "Commitment to sending daily reports before 10 p.m":
          "الالتزام بإرسال التقارير اليومية قبل الساعة 10م",
      "Commitment to send the start of work and send the photo at 10 am":
          "الالتزام بإرسال بدء العمل مع إرسال الصورة تمام الساعة 10 ص",
      "Postponing requests in the event of inability to complete them due to a reason":
          "عمل تأجيل للطلبات في حال عدم القدرة على إنجازها لوجود سبب",
      "Quick response to emergency requests":
          "سرعة الاستجابة مع الطلبات العاجلة",
      "Year": "السنة",
      "Month": "الشهر",
      "Technician alerts": "إنذارات الفنيين",
      "Sales": "المبيعات",
      "Maintenance request number invalid": "رقم طلب الصيانة المدخل غير صحيح",
      "Maintenance request number": "رقم طلب الصيانة",
      "Reason": "السبب",
      "New alert": "إنذار جديد",
      "Manage technician alerts": "إدارة الإنذارات",
      "Alert reason": "سبب الإنذار",
      "Edit alert": "تعديل الإنذار",
      "Technician": "الفني",
      "Alert number": "رقم الإنذار",
      "View alert": "عرض الإنذار",
      "Alert date": "تاريخ الإنذار",
      "Search by alert no": "بحث برقم الإنذار",
      "Not sent": "لم يتم الإرسال",
      "Technician alerts permissions": "صلاحيات إنذارات الفنيين",
      "View all": "الاطلاع على الجميع",
      "View own": "الاطلاع على ما يخصني",
      "Warranty expired": "منتهي الضمان",
      "Warranty status": "حالة الضمان",
      "true": "نعم",
      "false": "لا",
      "Available": "متوفر",
      "Not available": "غير متوفر",
      "Maximum daily orders limit": "الحد الأعلى للطلبات اليومية",
      "Maximum daily maintenance requests limit": "الحد اليومي لطلبات الصيانة",
      "Enter number of maximum daily maintenance requests under this category":
          "أدخل العدد الأعلى المسموح به لهذا النوع",
      "Sorry, we are no longer accepting this type of request at the moment, try choosing another time or maintenance type":
          "عذرا، لم نعد نقبل هذا النوع من الطلبات في الوقت الحالي، حاول اختيار وقت أو نوع صيانة آخر",
      "Exceptions": "استثناءات",
      "Add exception": "إضافة استثناء",
      "Remove exception": "حذف استثناء",
      "Invoice No": "رقم الفاتورة",
      "Statement": "البيان",
      "Manage financial settlement": "إدارة العهدة",
      "Financial settlements": "العهدة المالية",
      "General": "عام",
      "ComprehensiveWarranty": "الضمان الشامل",
      "OwnersUnion": "اتحاد ملاك",
      "CompanyExpenses": "مصروفات مكين",
      "OwnersAssociation": "جمعية ملاك",
      "Search by invoice no": "بحث برقم الفاتورة",
      "Total custody received": "إجمالي العهدة المستلم",
      "Expenses total": "إجمالي المصروفات",
      "Previous financial settlement total": "رصيد العهدة السابقة",
      "Total financial settlement received": "إجمالي العهدة المستلم",
      "Current financial settlement total": "الرصيد الحالي",
      "Previous financial settlement number": "رقم العهدة السابقة",
      "Financial settlement number invalid": "رقم العهدة غير صحيح",
      "Difference": "الصافي",
      "Tax amount": "ض.ق.م",
      "Invoice total": "إجمالي الفاتورة",
      "App version": "نسخة البرنامج",
      "Password reset": "إعادة تعيين كلمة السر",
      "We have reset your password you can login now":
          "تم إعادة تعيين كلمة السر، يمكنك تسجيل الدخول الآن",
      "Unable to reset": "تعذر إعادة تعيين كلمة السر",
      "Attempting to reset password": "جاري إعادة تعيين كلمة السر",
      "Daily checks": "الاستلامات اليومية",
      "Financial settlement permissions": "صلاحيات العهدة المالية",
      "Daily checks permissions": "صلاحيات الاستلامات اليومية",
      "Evening": "مساء",
      "Morning": "صباحا",
      "Elevators": "المصاعد",
      "Tanks": "الخزانات",
      "Cameras": "الكاميرات",
      "Sauna": "الساونا",
      "Jacuzzi": "الجاكوزي",
      "SwimmingPool": "المسبح",
      "Not fit": "غير لائق",
      "NotFit": "غير لائق",
      "Fit": "لائق",
      "Lounge": "اللاونج",
      "Search by no": "بحث بالرقم",
      "Include tax": "شامل الضريبة",
      "Without tax": "بدون ضريبة",
      "Attend": "تسجيل حضور",
      "Leave": "انصراف",
      "Total invoice": "إجمالي الفاتورة",
      "Type of expense": "نوع المصروف",
      "Financial settlement": "العهدة المالية",
      "Save and continue": "حفظ ومتابعة",
      "Complaints number": "رقم الشكوى",
      "Urgent request": "طلب طارئ",
      "Dear customer, this form is for emergency requests only":
          "عزيزي العميل هذا النموذج خاص بطلبات الطوارئ فقط",
      "There is notes": "يوجد ملاحظات",
      "Service not available now": "الخدمة غير متاحة الآن",
      "For clients only": "خاص بالعملاء فقط",
      "Default zone": "مركز التكلفة",
      "Another zone": "منطقة التبصيم",
      "Must be 4 numbers and in english":
          "يجب إدخال 4 أرقام فقط وباللغة الإنجليزية",
      "CommonParts": "الأجزاء المشتركة",
      "MakeenProjects": "مشاريع مكين",
      "Manufactory": "المصنع",
      "Only has default zone": "لديه مركز تكلفة",
      "New client": "عميل جديد",
      "Add for clients": "إضافة الطلبات للعملاء",
      "Attendance departure schedule": "جدول الحضور والغياب",
      "Absent": "غائب",
      "Present": "حاضر",
      "Vacation": "إجازة",
      "Absence total": "إجمالي الغياب",
      "Attendance total": "إجمالي الحضور",
      "Vacations total": "إجمالي الإجازات",
      "Gather": "تجميع",
      "Technician name": "اسم الفني",
      "View total report": "الاطلاع على التقرير الإجمالي",
      "Your device does not support camera capture. Please use a device with camera support":
          "جهازك لا يدعم التقاط الصور بالكاميرا. يرجى استخدام جهاز يدعم الكاميرا",
      "Take photo": "التقاط صورة",
      "Maintenance days": "أيام الصيانة",
      "Project maintenance day permissions": "صلاحيات إعدادات أيام الصيانة",
      "Manage available days for project maintenance":
          "إدارة الأيام المتاحة لصيانة المشروع",
      "Days available for maintenance": "الأيام المتاحة للصيانة",
      "Add a new request related to this request":
          "إضافة طلب جديد متعلق بهذا الطلب",
      "Activate this option if the current maintenance needs to be followed up by another technician":
          "قم بتفعيل هذا الخيار في حال كانت الصيانة الحالية تحتاج لمتابعة من قبل فني آخر",
      "Cant send code": "فشل إرسال الرمز",
      "Inquire about the status of the request": "استعلام عن حالة الطلب",
      "Enter request code": "أدخل كود الطلب",
      "Request status": "حالة الطلب",
      "Request not found": "الطلب غير موجود",
      "Customizing maintenance dates": "تخصيص تواريخ الصيانة",
      "The current issue related to a previous reported request":
          "تتعلق المشكلة الحالية بطلب سابق تم الإبلاغ عنه",
      "Example: 0000 or MA1-000000": "مثال: 0000 أو MA1-000000",
      "Number or coding of the previous order": "رقم أو تكويد الطلب السابق",
      "Maintenance request invalid": "الطلب غير موجود",
      "Job number": "الرقم الوظيفي",
      "You can not check out at this time":
          "لا يمكنك تسجيل الخروج في هذا الوقت",
      "OutOfShiftCheckOut": "خارج الوردية المحدد الدوام",
      "Vacations permissions": "صلاحيات الإجازات",
      "Letters permissions": "صلاحيات الخطابات",
      "Letters": "الخطابات",
      "Letters management": "إدارة الخطابات",
      "Letter file": "ملف الخطاب",
      "Letter number": "رقم الخطاب",
      "Letter title": "عنوان الخطاب",
      "Letter date": "تاريخ الخطاب",
      "Search by letter no": "بحث برقم الخطاب",
      "Letter": "خطاب",
      "FormalPaper": "ورق رسمي",
      "Warranty expires on": "ينتهي الضمان في",
      "Employee vacations": "إجازات الموظفين",
      "Add Clients": "إضافة عملاء",
      "Number of extra visits": "عدد الزيارات الإضافية",
      "Employee evaluations": "تقييمات الموظفين",
      "New evaluation": "تقييم جديد",
      "Manage evaluations": "إدارة التقييمات",
      "Select evaluation form": "اختر نموذج التقييم",
      "Employee evaluation submission": "تقييمات الموظفين",
      "Select employee to evaluate": "اختر الموظف المراد تقييمه",
      "Evaluation form": "نموذج التقييم",
      "Please answer all questions": "أجب على جميع الأسئلة",
      "Form": "النموذج",
      "First period from 9 AM to 12 PM": "الفترة الأولى ٩ص - ١٢م",
      "Second period from 4 PM to 9 PM": "الفترة الثانية ٤م - ٩م",
      "HeadOfDepartment": "مدير إدارة / مشرف قسم",
      "ProjectManager": "مدير مشروع",
      "CEOAssistant": "مساعد الرئيس التنفيذي",
      "An employee": "موظف",
      "Requests": "الطلبات",
      "New note": "ملاحظة جديدة",
      "Search by title": "بحث بالعنوان",
      "Manage Un Evaluated": "إدارة النماذج الغير مقيمة",
      "Employee evaluation forms permissions": "صلاحيات نماذج تقييم الموظفين",
      "Search by visit title": "بحث بعنوان الزيارة",
      "Stock visits": "زيارات المستودع",
      "Visit title": "عنوان الزيارة",
      "Number of units": "عدد الوحدات",
      "Approved project price per unit":
          "قيمة المشروع المعتمدة بالنسبة لعدد الوحدات",
      "Camera in front of the stock": "كاميرا أمام باب المستودع",
      "Bobcat in front of the stock": "بوبكات أمام المستودع",
      "Storage safety": "سلامة التخزين",
      "Alarm bell": "جرس إنذار",
      "Stock requirements": "اشتراطات المستودع",
      "Fire extinguisher": "طفاية حريق",
      "Increases": "الزيادات",
      "Receipt requests": "طلبات الاستلام",
      "Receipt requests management": "إدارة طلبات الاستلام",
      "Suitable": "سليمة",
      "Not suitable": "غير سليمة",
      "New product": "منتج جديد",
      "Return to supplier": "يعاد للمورد",
      "Transfer to": "ينقل إلى",
      "Client property inquiry permissions": "صلاحيات اهتمامات العملاء",
      "Clients inquiries": "اهتمامات العملاء",
      "Number of rooms": "عدد الغرف",
      "Area": "المساحة",
      "Property type": "نوع العقار",
      "Villa": "فلة",
      "Apartment": "شقة",
      "Search by inquiry": "بحث بالاهتمام",
      "Whatsapp number": "رقم الواتسأب",
      "Inquiries list": "قائمة الاهتمامات",
      "Clients list": "قائمة العملاء",
      "Inquiries count": "عدد الاهتمامات",
      "Last inquiry": "أحدث اهتمام",
      "Edit client": "تعديل العميل",
      "New inquiry": "تسجيل اهتمام جديد ",
      "TownHouse": "تاون هاوس",
      "Floor": "دور",
      "Quality notes": "ملاحظات الجودة",
      "Note number": "رقم الملاحظة",
      "Marketers": "المسوقين",
      "Marketer": "المسوق",
      "Link": "ربط",
      "Import": "استيراد",
      "Download template": "تنزيل القالب",
      "Importing": "جاري الاستيراد",
      "WhatsApp": "واتسأب",
      "Make Call": "اتصال",
      "First Period": "الفترة الأولى",
      "Second Period": "الفترة الثانية",
      "Maintenance periods": "فترات الصيانة",
      "Contacted": "تم الاتصال",
      "FollowUpRequired": "يتطلب متابعة",
      "Completed": "تم الانتهاء",
      "Unreachable": "غير قابل للوصول",
      "Contact summery": "ملخص الاتصال",
      "Inquiry": "الاهتمام",
      "Clients": "العملاء",
      "Client inquiries": "اهتمامات العميل",
      "Contacts": "التوصل",
      "㎡": "م²",
      "Call": "مكالمة",
      "Corridor": "الممر",
      "Note location": "مكان الملاحظة",
      "Date to contact": "وقت التواصل",
      "Contact date": "تاريخ التواصل",
      "Assign marketers": "إسناد المسوقين",
      "Contact status": "حالة التواصل",
      "Maintenance assessments permissions": "صلاحيات تقييمات الصيانة",
      "Called clients": "عميل تم الاتصال به",
      "Client identity": "رقم هوية العميل",
      "Client phone": "جوال العميل",
      "Client email": "إيميل العميل",
      "Client nationality": "جنسية العميل",
      "Bookings": "الحجوزات",
      "Manage bookings": "إدارة الحجوزات",
      "New booking": "حجز جديد",
      "Booking no": "رقم الحجز",
      "Attach a copy of the transfer": "إرفاق صورة الحوالة",
      "Edit booking": "تعديل الحجز",
      "The ID number must contain between 10 and 15 digits and not start with zero":
          "رقم الهوية يجب أن لا يقل عن 10 أرقام ولا يزيد عن 15 رقما ولا يبدأ بصفر",
      "Buy": "شراء",
      "Rent": "تأجير",
      "Enter discount in riyal": "أدخل الخصم بالريال",
      "Attach a copy of the exemption": "إرفاق صورة الإعفاء",
      "Selected price range": "حدود السعر المطلوب",
      "Deposit": "العربون",
      "Reserved by marketer": "محجوز من قبل المسوق",
      "Enter deposit in riyal": "أدخل العربون بالريال",
      "Enter price in riyal": "أدخل السعر بالريال",
      "Number of Today Connected Clients": "عدد من تم الاتصال بهم اليوم",
      "Number of Today Clients": "عدد عملاء اليوم",
      "Marketers total": "عدد المسوقين",
      "Clients total": "عدد العملاء",
      "Interested clients": "العملاء المهتمين",
      "Commission": "السعي",
      "Commission tax": "ضريبة السعي",
      "Total commission": "إجمالي السعي",
      "Price including commission": "سعر الوحدة شامل السعي",
      "Property status": "حالة العقار",
      "Occupied": "مشغول",
      "UnderMaintenance": " تحت الصيانة",
      "Reserved": "محجوز",
      "UnSupportedBank": "بنك غير مدعوم",
      "Has tax free": "معفى ضريبيا",
      "Without inquiry": "بدون اهتمام",
      "Ratio": "نسبة",
      "Reserved ratio": "نسبة الحجز",
      "Supplier name": "اسم المورد",
      "Suppliers management": "إدارة الموردين",
      "Suppliers": "الموردين",
      "Stock entry receipt number": "رقم سند ادخال المستودع",
      "Purchases": "المشتريات",
      "Purchases management": "إدارة المشتريات",
      "Search by invoice number": "بحث برقم الفاتورة",
      "Purchase number": "رقم البيان",
      "Statement number": "رقم البيان",
      "Purchase statement number": "رقم بيان المشتريات",
      "Total of quantities": "إجمالي الكميات",
      "Total of prices": "إجمالي السعر",
      "New supplier": "مورد جديد",
      "Unit price": "سعر الوحدة",
      "The net": "الصافي",
      "Warranty end date": "تاريخ انتهاء الضمان",
      "Buyer": "المشتري",
      "Attach a copy of the invoice": "إرفاق صورة الفاتورة",
      "Purchase return": "مرتجع المشتريات",
      "Stock exit receipt number": "رقم سند إخراج من المستودع",
      "Purchase invoice number": "رقم فاتورة الشراء",
      "Returner": "القائم بالرجيع",
      "Return reason": "سبب الإرجاع",
      "Purchaser statement number": "رقم بيان المشترى",
      "Purchase statement number invalid": "رقم بيان المشتري غير صحيح",
      "Expenditures": "المنصرف",
      "Expenditures management": "إدارة المنصرف",
      "Expenditure return": "رجيع المنصرف",
      "Expenditure number": "رقم بيان المنصرف",
      "Expenditure statement number invalid": "رقم بيان المنصرف غير صحيح",
      "Corruptions": "التوالف",
      "Expenditure return number": "رقم بيان رجيع المنصرف",
      "Unit Permissions": "صلاحيات الوحدات السكنية",
      "View Units": "الاطلاع على الوحدات",
      "Manage Units": "إدارة الوحدت",
      "Suppliers Permissions": "صلاحيات الموردين",
      "Quality Notes Permissions": "صلاحيات ملاحظات الجودة",
      "Bookings permissions": "صلاحيات الحجوزات",
      "Employee evaluation submission permissions": "صلاحيات تقييمات الموظفين",
      "Stock visits permissions": "صلاحيات زيارات المستودع",
      "Purchase permissions": "صلاحيات المشتريات",
      "Purchase returns permissions": "صلاحيات مرتجع المشتريات",
      "Expenditure permissions": "صلاحيات منصرف المشتريات",
      "Expenditure return permissions": "صلاحيات مرتجع منصرف المشتريات",
      "Participant permissions": "صلاحيات المساهمين",
      "Assets permissions": "صلاحيات الأصول",
      "Invoices permissions": "صلاحيات الفواتير",
      "Purchase corruptions permissions": "صلاحيات توالف المشتريات",
      "Quality Reports Permissions": "صلاحيات تقارير الجودة",
      "Manage Own Companies": "إدارة الشركات التي تخصني",
      "View Own Companies": "الاطلاع على الشركات التي تخصني",
      "Manage own": "إدارة ما يخصني",
      "Main department": "الإدارة الرئيسية",
      "No users available in this department":
          "لا يوجد مستخدمون في هذه الإدارة/القسم",
      "AfterSalesSpecialist": "أخصائي خدمات ما بعد البيع",
      "SeniorAfterSalesSpecialist": "كبير أخصائي خدمات ما بعد البيع",
      "ReservationsSpecialist": "أخصائي حجوزات",
      "Accountant": "محاسب",
      "SalesSpecialist": "أخصائي مبيعات",
      "MarketingSpecialist": "أخصائي تسويق",
      "DigitalMarketingSpecialist": "أخصائي تسويق رقمي",
      "GraphicDesigner": "مصمم جرافيك",
      "CallCenterSpecialist": "أخصائي مركز اتصال",
      "CallCenterSupervisor": "مشرف مركز اتصال",
      "EventSupervisor": "مشرف الفعاليات",
      "MaintenanceSupervisor": "مشرف الصيانة",
      "PoolTechnician": "فني مسابح",
      "Painter": "فني دهان",
      "PlumbingTechnician": "فني سباكة",
      "ElectricalTechnician": "فني كهرباء",
      "FieldSupervisor": "مشرف ميداني",
      "EngineeringManager": "مدير الإدارة الهندسية",
      "MechanicalEngineer": "مهندس ميكانيكا",
      "ElectricalEngineer": "مهندس كهرباء",
      "CivilEngineer": "مهندس مدني",
      "ArchitecturalEngineer": "مهندس معماري",
      "QualityEngineer": "مهندس جودة",
      "ProjectQualityManager": "مدير جودة المشاريع",
      "ProcurementManager": "مدير المشتريات",
      "ITSpecialist": "أخصائي تقنية المعلومات",
      "HRManager": "مدير الموارد البشرية",
      "FinancialManager": "المدير المالي",
      "PayrollSpecialist": "أخصائي الرواتب",
      "RecruitmentSpecialist": "أخصائي التوظيف",
      "BusinessDevelopmentManager": "مدير تطوير الأعمال",
      "Me": "لي",
      "To me": "إلي",
      "CEO": "الرئيس التنفيذي",
      "ManagingDirector": "العضو المنتدب",
      "Chairman": "رئيس مجلس الإدارة",
      "Search job": "بحث في المسميات الوظيفية",
      "MaintenanceRequests": "طلبات الصيانة",
      "CleaningAndHospitality": "منظفات وضيافة",
      "Paid service request": "طلب خدمة مدفوعة",
      "FitBy0": "0",
      "FitBy25": "25",
      "FitBy50": "50",
      "FitBy75": "75",
      "FitBy100": "100",
      "Fit percentage": "لائق بنسبة",
      "Percentage": "النسبة المئوية",
      "Finish": "إنهاء",
      "Report": "تقرير",
      "Secretary": "سكرتير",
      "ExecutiveVicePresident": "نائب الرئيس التنفيذي",
      "UnifiedContactCenterSpecialist": "أخصائي مركز اتصال موحد",
      "TraditionalMarketingSpecialist": "أخصائي تسويق تقليدي",
      "TeamLeader": "قائد فريق",
      "CustomerServiceSupervisor": "مشرف قسم خدمة العملاء",
      "DailyRentalSpecialist": "أخصائي تأجير يومي",
      "AnnualRentalSpecialist": "أخصائي تأجير سنوي",
      "FinancialAndAdministrativeSpecialist": "أخصائي شؤون مالية وإدارية",
      "SharedPartsSupervisor": "مشرف قسم الأجزاء المشتركة",
      "AfterSalesSupervisor": "مشرف قسم خدمات ما بعد البيع",
      "AuditManager": "مدير إدارة المراجعة الداخلية",
      "InternalAuditSpecialist": "أخصائي مراجعة داخلية",
      "QualityInspector": "أخصائي جودة",
      "EmployeeEngagementSupervisor": "مشرف قسم إسعاد الموظفين",
      "LegalAffairsManager": "مدير الإدارة القانونية",
      "AssistantSurveyor": "مساعد مساح",
      "CompensationAndPayrollSpecialist": "أخصائي الرواتب والتعويضات",
      "HospitalityOperationsManager": "مدير إدارة التشغيل الفندقي",
      "Department leader": "رئيس إدارة أو قسم",
      "View Client Users": "الاطلاع على العملاء",
      "View Employees": "الاطلاع على الموظفين",
      "Add Client Users": "إضافة عملاء",
      "Abbreviation": "الاسم المختصر",
      "Yellow": "أصفر",
      "Red": "أحمر",
      "Help": "مساعدة",
      "Personal Settings": "الإعدادات الشخصية",
      "My Profile": "ملفي الشخصي",
      "Saved Addresses": "العناوين المحفوظة",
      "App Settings": "إعدادات التطبيق",
      "Rate App": "قيم التطبيق",
      "Support & Help": "الدعم والمساعدة",
      "Chat with Support": "دردشة مع خدمة العملاء",
      "WhatsApp Contact": "تواصل واتساب",
      "General Settings": "إعدادات عامة",
      "About Us": "عن التطبيق",
      "Privacy Policy": "سياسة الخصوصية",
      "Account Actions": "إجراءات الحساب",
      "Delete Account": "حذف الحساب",
      "Log Out": "تسجيل الخروج",
    },
  };

  /// Returns the translated string for the given key
  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

/// **Extension to Use `context.tr()` Globally**
extension TranslateExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this).translate(key);
  }
}

/// **Localization Delegate for `MaterialApp`**
class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
